DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
-- CREATE TABLE LIBRARY(
-- BOOK_ID BIGINT FOREIGN KEY ,
-- AUTHOR_ID  FOREIGN KEY,
-- GENRE_ID BIGINT FOREIGN KEY,
-- );
