spring:
  data:
    mongodb:
      authentication-database: none
      database: library
      port: 27017
      host: localhost

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  batch:
    job:
      enabled: true