spring:
  data:
    mongodb:
      authentication-database: none
      database: library
      port: 27017
#      host: localhost
      host: ${MONGO_HOST}
users: user:{noop}userpass,admin:{noop}adminpass,guest:{noop}guestpass
