spring:
  data:
    mongodb:
      authentication-database: none
      database: library
      port: 27017
      host: localhost
users: user:{noop}userpass,admin:{noop}adminpass,guest:{noop}guestpass
